### ISSUE TITLE
`vp_file_read()` returns 4096 bytes in output but it returns eof

### ISSUE THREAD

**Issue by Shougo** [Shougo/vimproc.vim#195]
I tested https://github.com/Shougo/unite.vim/issues/904 problem.
And I found vimproc's `vp_file_read()` returns only 4096 bytes in the output and returns eof.
It seems buffering problem.  But I cannot find 4096 bytes buffer in vimproc.

**Comment by Shougo** [comment]
@ichizok Can you test the problem?

**Comment by ichizok** [comment]
Certainly.

**Comment by Shougo** [comment]
It is fixed in latest vimproc version.
@ichizok Thanks.

**Comment by Ram-Z** [comment]
I can still reproduce the problem in https://github.com/Shougo/unite.vim/issues/904 after updating all plugins and rebuilding vimproc.

Running `test.c` from #197 I get
```
$ gcc test.c -lutil
$ ./a.out
revents=0011
read 4095 bytes (4095/16384)
revents=0010
POLLHUP
```

However running it in a loop will sometimes allow me to [get 8192 bytes](https://gist.github.com/Ram-Z/a1a9033bafa7592f7319#file-gistfile1-txt) before the PULLHUP. However if I pipe the output to a file this will [not happen](https://gist.github.com/Ram-Z/a1a9033bafa7592f7319#file-gistfile2-txt).

I'm runnig glibc 2.20 and linux 3.19.1 if that's any help.

**Comment by ichizok** [comment]
@Ram-Z Could you run this test2.c? 
https://gist.github.com/ichizok/919ab51d36981ca90216#file-test2-c

It should behave same as latest vimproc.

**Comment by Ram-Z** [comment]
```
% gcc test2.c -lutil && ./a.out 
revents=0011
read 4095 bytes (4095/16384)
revents=0010
detected EOF? (POLLHUP)
```

**Comment by Shougo** [comment]
I tested it in Ubuntu 14.04:

```
$ gcc test2.c -lutil && ./a.out 
test2.c: In function ‘main’:
test2.c:100:13: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘unsigned int’ [-Wformat=]
             printf("read %d bytes (%lu/%lu)\n", n, sizeof(b)-cnt, sizeof(b));
             ^
test2.c:100:13: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘unsigned int’ [-Wformat=]
revents=0011
read 4095 bytes (4095/16384)
revents=0011
read 4095 bytes (8190/16384)
revents=0011
read 2 bytes (8192/16384)
revents=0010
detected EOF? (POLLHUP)
```

Hmmm...
Different result.

**Comment by ichizok** [comment]
@Ram-Z Thank you. then could you run test3.c? I tried setting pty non-caconical.
https://gist.github.com/ichizok/919ab51d36981ca90216#file-test3-c

**Comment by Ram-Z** [comment]
```
[23:36 ramsi@shada]% gcc test3.c -lutil && ./a.out
#ICANON=1, VTIME=0, VMIN=1
revents=0011
read 4095 bytes (4095/16384)
revents=0010
error: Input/output error
detected EOF? (POLLHUP)


[23:36 ramsi@shada]% gcc test3.c -lutil && ./a.out
#ICANON=1, VTIME=0, VMIN=1
revents=0011
read 4095 bytes (4095/16384)
revents=0010
read 4095 bytes (8190/16384)
revents=0011
read 2 bytes (8192/16384)
revents=0010
error: Input/output error
detected EOF? (POLLHUP)

**Comment by Shougo** [comment]
@ichizok From @mattn analyse, it seems the forked process exits after write bytes.
So, vimproc can only get buffered string.
pipe/pty difference is just buffer size.

**Comment by Shougo** [comment]
I think vimproc must change buffering behavior in pty.

**Comment by Shougo** [comment]
I tested it in latest vimproc.  It works. Closing.
