### ISSUE TITLE
Vim 7.4.851 is broken

### ISSUE THREAD

**Issue by Shougo** [Shougo/vimproc.vim#208]
https://github.com/Shougo/neocomplete.vim/issues/471

vimproc created vim as subprocess.  But it is crashed(failed to create new console?).
I think it is fatal problem.

I cannot test the problem.
Because, to test it, I need latest Windows Vim binary.
But I have not it.

@k-takata is the original patch author.  So you are best assignee for the problem.

https://github.com/vim-jp/issues/issues/732

**Comment by petobens** [comment]
There is a vim 7.4.872 binary [here](https://tuxproject.de/projects/vim/).

**Comment by k-takata** [comment]
Fixed with Vim 7.4.876.

**Comment by Shougo** [comment]
Thanks.

**Comment by Shougo** [comment]
It is not fixed yet.
Because, Vim 7.4.876 only works in Windows 7.

**Comment by Shougo** [comment]
I cannot reproduce it in Windows 7 environment...

**Comment by k-takata** [comment]
7.4.851 has been reverted by 7.4.902.
https://groups.google.com/d/topic/vim_dev/6bGV04XzMs0/discussion

**Comment by Shougo** [comment]
OK.  Thanks!

**Comment by KazuakiM** [comment]
Thanks!
